INSERT INTO Song (title, songLength, artist) VALUES ('Bad Guy',3,'Billie Eilish');
INSERT INTO Song (title, songLength, artist) VALUES ('Old Town Road',2,'Lil Nas X');
INSERT INTO Song (title, songLength, artist) VALUES ('Sucker',6,'Jonas Brothers');
INSERT INTO Song (title, songLength, artist) VALUES ('How Do You Sleep?',4,'Sam Smith');
INSERT INTO Song (title, songLength, artist) VALUES ('Panini',3,'Lil Nas X');
INSERT INTO Song (title, songLength, artist) VALUES ('Truth Hurts',6,'Lizzo');
INSERT INTO Song (title, songLength, artist) VALUES ('Motivation',3,'Normani');
INSERT INTO Song (title, songLength, artist) VALUES ('Slide Away',5,'Miley Cyrus');
INSERT INTO Song (title, songLength, artist) VALUES ('break up with your girlfriend',4,'Ariana Grande');
INSERT INTO Song (title, songLength, artist) VALUES ('Talk',7,'Khalid');
INSERT INTO Song (title, songLength, artist) VALUES ('I Don’t Care',4,'Justin Bieber');
INSERT INTO Song (title, songLength, artist) VALUES ('Liar',8,'Camila Cabello');
INSERT INTO Song (title, songLength, artist) VALUES ('No Guidance',4,'Chris Brown');
INSERT INTO Song (title, songLength, artist) VALUES ('One Thing Right',5,'Kane Brown');
INSERT INTO Song (title, songLength, artist) VALUES ('Hot Girl Summer',3,'Megan Thee Stallion');
INSERT INTO Song (title, songLength, artist) VALUES ('Don’t Call Me Up',5,'Mabel');
INSERT INTO Song (title, songLength, artist) VALUES ('See You Again',7,'Mark Ronson');
INSERT INTO Song (title, songLength, artist) VALUES ('Harder',2,'Jax Jones');
INSERT INTO Song (title, songLength, artist) VALUES ('Good Thing',7,'Zedd');